### ISSUE TITLE
Creating and dispatching two trains leaves one unable to launch

### ISSUE THREAD

**Issue by ryanbecker33** [BurlingtonCodeFactory/NorthShoreExtension#44]
Steps to reproduce:
1. Load up the green line
2. Create and dispatch a train
3. Create and dispatch another train
4. Set speed and authority for train 1

Result:
Speed and authority for train 1 go to null

**Comment by rats3g** [comment]
Tried to reproduce this issue, found that Train 1 proceeds to destination at speed set. However, found issue that the TrainModel UI for Trains 1 and 2 both showed the values for Train 1. Also, when setting a speed and authority for train 2 it does not go. If you create and dispatch train 3, then train 2 proceeds to destination with the Train 3 UI showing values for what appears to be Train 2. @evanozaroff
